// src/components/application/ApplicationForm.vue
<template>
  <h1>연세 골프 지원서</h1>
  <div class="before-apply">* 지원서는 임시저장되지 않습니다.</div>
  <div class="before-apply">*지원서 작성 시 이모지 사용을 자제해주세요. 이모지 사용으로 인한 불이익은 지원자에게 있습니다.</div>
  <table class="profile-info">
    <tbody>
    <tr>
      <td rowspan="2">
        사진
      </td>
      <td rowspan="2">
        <div class="file-upload-container">
          <input v-if="!applications.photo" type="file" @change="handleFileUpload"/>
          <button class="photo-button" v-if="!applications.photo" @click="uploadImage">사진 업로드</button>
        </div>
        <img class="apply-photo" v-if="applications.photo" :src="applications.photo"/>
      </td>
      <td>
        이름
      </td>
      <td>
        <textarea placeholder="김연골" v-model="applications.name" @input="handleNameInput"></textarea>
      </td>
    </tr>

    <tr>
      <td>나이</td>
      <td>
        <textarea placeholder="숫자만 입력해주세요" v-model="applications.age" @input="handleAgeInput"></textarea>
      </td>
    </tr>

    <tr>
      <td>
        학번
      </td>
      <td>
        <textarea placeholder="숫자만 입력해주세요" v-model="applications.studentId" @input="handleStudentIdInput"></textarea>
      </td>
      <td>
        전공
      </td>
      <td>
        <textarea placeholder="OO학과" v-model="applications.major" @input="handleMajorInput"></textarea>
      </td>
    </tr>

    <tr>
      <td>
        전화번호
      </td>
      <td>
        <textarea placeholder="숫자만 입력해주세요" v-model="applications.phoneNumber"
                  @input="handlePhoneNumberInput"></textarea>
      </td>

      <td>
        이메일
      </td>
      <td>
        <textarea placeholder="yonseigolf@email.com" v-model="applications.email" @input="handleEmailInput"></textarea>
      </td>
    </tr>

    <tr>
      <td>
        구력
      </td>
      <td>
        <select v-model="applications.golfDuration">
          <option value="0">1년 미만</option>
          <option value="1">1년</option>
          <option value="2">2년</option>
          <option value="3">3년</option>
          <option value="4">4년</option>
          <option value="5">5년 이상</option>
        </select>
      </td>

      <td>
        라운딩 횟수
      </td>
      <td>
        <select v-model="applications.roundCount">
          <option value="0">0회</option>
          <option value="1">1회</option>
          <option value="2">2회</option>
          <option value="3">3회</option>
          <option value="4">4회</option>
          <option value="5">5회 이상</option>
        </select>
      </td>
    </tr>

    <tr>
      <td>
        레슨 여부
      </td>
      <td>
        <select v-model="applications.lessonStatus">
          <option value="true">레슨 x</option>
          <option value="false">레슨 o</option>
        </select>
      </td>
      <td>
        본인 클럽 소유 여부
      </td>
      <td>
        <select v-model="applications.clubStatus">
          <option value="true">보유중</option>
          <option value="false">보유하지 않음</option>
        </select>
      </td>
    </tr>
    </tbody>
  </table>

  <table class="application-body">
    <thead>
    <tr>
      <th>
        1. 간략하게 자기소개 부탁드립니다. (군대 계획이나 교환학생 계획이 있다면 적어주세요)
      </th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td>
        <textarea placeholder="최대 500자까지 작성 가능합니다." v-model="applications.selfIntroduction" rows="30"
                  @input="handleSelfIntroductionInput"></textarea>
        <div class="error-message" v-if="selfInfoInvalid"> 최대 500자까지 작성 가능합니다.</div>
      </td>
    </tr>
    </tbody>

    <thead>
    <tr>
      <th>
        2. 연세 골프에 지원하게 된 동기를 작성해주세요
      </th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td>
        <textarea placeholder="최대 500자까지 작성 가능합니다." v-model="applications.applyReason" rows="30"
                  @input="handleApplyReasonInput"></textarea>
        <div class="error-message" v-if="applyReasonInvalid"> 최대 500자까지 작성 가능합니다.</div>
      </td>
    </tr>
    </tbody>

    <thead>
    <tr>
      <th>
        3. 현재 본인의 골프 실력을 객관적으로 평가해주세요.
      </th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td>
        <textarea placeholder="최대 500자까지 작성 가능합니다." v-model="applications.skillEvaluation" rows="30"
                  @input="handleSkillEvaluationInput"></textarea>
        <div class="error-message" v-if="golfSkillInvalid"> 최대 500자까지 작성 가능합니다.</div>
      </td>
    </tr>
    </tbody>

    <thead>
    <tr>
      <th>
        4. 골프와 관련된 추억이 있으시다면 말씀해주세요
      </th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td>
        <textarea placeholder="최대 500자까지 작성 가능합니다." v-model="applications.golfMemory" rows="30"
                  @input="handleGolfMemoryInput"></textarea>
        <div class="error-message" v-if="golfMemoryInvalid"> 최대 500자까지 작성 가능합니다.</div>
      </td>
    </tr>
    </tbody>

    <thead>
    <tr>
      <th>
        5. 현재 활동하는 다른 동아리나 학회가 있다면 적어주세요
      </th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td>
        <textarea placeholder="최대 500자까지 작성 가능합니다." v-model="applications.otherClub" rows="30"
                  @input="handleOtherClubInput"></textarea>
        <div class="error-message" v-if="otherClubInvalid"> 최대 500자까지 작성 가능합니다.</div>
      </td>
    </tr>
    </tbody>

    <thead>
    <tr>
      <th>
        6. 본인의 스윙 영상이 담긴 url을 적어주세요 (유튜브, 인스타 등)
      </th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td>
        <textarea placeholder="유튜브 링크를 첨부해주세요. (비공개 영상이 아닌지 확인해주세요)" v-model="applications.swingVideo" rows="30"
                  @input="handleSwingVideoInput"></textarea>
        <p class="error-message" v-if="golfSwingInvalid"> 최대 500자까지 작성 가능합니다.</p>
      </td>
    </tr>
    </tbody>
  </table>
  <div>* 지원서 제출 전 이메일과 전화번호를 다시 한번 확인해주세요.</div>
  <div>* 결과는 이메일로 전송해드립니다.</div>
  <button class="apply-button" @click="submitApplication" type="submit">지원서 제출</button>
</template>

<script>
import axios from "axios";

export default {

  data() {
    return {
      applications: {
        name: '',
        photo: '',
        age: '',
        studentId: '',
        major: '',
        phoneNumber: '',
        email: '',
        golfDuration: 0,
        roundCount: 0,
        lessonStatus: false,
        clubStatus: false,
        selfIntroduction: '',
        applyReason: '',
        skillEvaluation: '',
        golfMemory: '',
        otherClub: '',
        swingVideo: '',
        selectedFile: null,
      },
      selfInfoInvalid: false,
      applyReasonInvalid: false,
      golfSkillInvalid: false,
      golfMemoryInvalid: false,
      otherClubInvalid: false,
      golfSwingInvalid: false
    }
  },

  methods: {
    async submitApplication() {
      if (this.isFormValid) {
        if (confirm(`지원서를 제출하시겠습니까? \n이메일로 결과가 발송되니 이메일을 다시 한번 확인해주세요 \n ${this.applications.email}`)) {
          try {
            const response =
                await axios.post(`${process.env.VUE_APP_API_URL}/application`, {
                  name: this.applications.name,
                  age: this.applications.age,
                  photo: this.applications.photo,
                  studentId: this.applications.studentId,
                  major: this.applications.major,
                  phoneNumber: this.applications.phoneNumber,
                  email: this.applications.email,
                  golfDuration: this.applications.golfDuration,
                  roundCount: this.applications.roundCount,
                  lessonStatus: this.applications.lessonStatus,
                  clubStatus: this.applications.clubStatus,
                  selfIntroduction: this.applications.selfIntroduction,
                  applyReason: this.applications.applyReason,
                  skillEvaluation: this.applications.skillEvaluation,
                  golfMemory: this.applications.golfMemory,
                  otherClub: this.applications.otherClub,
                  swingVideo: this.applications.swingVideo,
                });

            // 응답 처리
            if (response.status === 200) {
              alert(`${this.applications.email}로 지원서 접수 메일을 전송해드릴 예정입니다. 10분 내로 접수 메일을 받지 못했다면 인스타로 문의 부탁드립니다.`);
              this.$router.push('/');
            }
          } catch (error) {
            alert('지원서는 접수되었으나, 이메일 발송에 실패하였습니다. \n인스타를 통해 지원 문의 바랍니다.')
            this.$router.push('/');
          }
        }
      } else {
        alert('지원서 모든 항목을 작성해주세요.')
      }
    },

    async uploadImage() {
      const formData = new FormData();
      formData.append('image', this.applications.selectedFile);

      try {
        const response = await axios.post(`${process.env.VUE_APP_API_URL}/apply/forms/image`, formData, {
          headers: {
            'Content-Type': 'multipart/form-data'
          }
        });

        // 응답에서 이미지 URL을 가져와서 저장
        this.applications.photo = response.data.data.image;

      } catch (error) {
        console.error("Image upload failed:", error);
      }
    },

    handleFileUpload(event) {
      this.applications.selectedFile = event.target.files[0];
    },

    handleNameInput() {
      if (this.applications.name.length > 10) {
        this.applications.name = this.applications.name.substring(0, 10);
      }
    },

    handleAgeInput() {
      // 숫자만 입력되도록 필터링
      this.applications.age = this.applications.age.replace(/[^0-9]/g, '');

      // 2글자를 초과하면 잘라내기
      if (this.applications.age.length > 2) {
        this.applications.age = this.applications.age.substring(0, 2);
      }
    },

    handleStudentIdInput() {
      this.applications.studentId = this.applications.studentId.replace(/[^0-9]/g, '');

      if (this.applications.studentId.length > 11) {
        this.applications.studentId = this.applications.studentId.substring(0, 11);
      }
    },

    handleMajorInput() {
      if (this.applications.major.length > 10) {
        this.applications.major = this.applications.major.substring(0, 10);
      }
    },

    handlePhoneNumberInput() {
      this.applications.phoneNumber = this.applications.phoneNumber.replace(/[^0-9]/g, '');

      if (this.applications.phoneNumber.length > 11) {
        this.applications.phoneNumber = this.applications.phoneNumber.substring(0, 11);
      }
    },

    handleEmailInput() {
      if (this.applications.email.length > 30) {
        this.applications.email = this.applications.email.substring(0, 30);
      }
    },

    handleSelfIntroductionInput() {
      if (this.applications.selfIntroduction.length > 500) {
        this.applications.selfIntroduction = this.applications.selfIntroduction.substring(0, 500);
      }
      this.selfInfoInvalid = this.applications.selfIntroduction.length >= 500;
    },

    handleApplyReasonInput() {
      if (this.applications.applyReason.length > 500) {
        this.applications.applyReason = this.applications.applyReason.substring(0, 500);
      }
      this.applyReasonInvalid = this.applications.applyReason.length >= 500;
    },

    handleSkillEvaluationInput() {
      if (this.applications.skillEvaluation.length > 500) {
        this.applications.skillEvaluation = this.applications.skillEvaluation.substring(0, 500);
      }
      this.golfSkillInvalid = this.applications.skillEvaluation.length >= 500;
    },

    handleGolfMemoryInput() {
      if (this.applications.golfMemory.length > 500) {
        this.applications.golfMemory = this.applications.golfMemory.substring(0, 500);
      }
      this.golfMemoryInvalid = this.applications.golfMemory.length >= 500;
    },

    handleOtherClubInput() {
      if (this.applications.otherClub.length > 500) {
        this.applications.otherClub = this.applications.otherClub.substring(0, 500);
      }
      this.otherClubInvalid = this.applications.otherClub.length >= 500;
    },

    handleSwingVideoInput() {
      if (this.applications.swingVideo.length > 500) {
        this.applications.swingVideo = this.applications.swingVideo.substring(0, 500);
      }
      this.golfSwingInvalid = this.applications.swingVideo.length >= 500;
    },
  },

  computed: {
    applicationNameInput: {
      get() {
        return this.applications.name;
      },
      set(val) {
        this.applications.name = val;
      }
    },

    applicationAgeInput: {
      get() {
        return this.applications.age;
      },
      set(val) {
        this.applications.age = val;
      }
    },

    applicationStudentIdInput: {
      get() {
        return this.applications.studentId;
      },
      set(val) {
        this.applications.studentId = val;
      }
    },

    applicationMajorInput: {
      get() {
        return this.applications.major;
      },
      set(val) {
        this.applications.major = val;
      }
    },

    applicationPhoneNumberInput: {
      get() {
        return this.applications.phoneNumber;
      },
      set(val) {
        this.applications.phoneNumber = val;
      }
    },

    applicationEmailInput: {
      get() {
        return this.applications.email;
      },
      set(val) {
        this.applications.email = val;
      }
    },

    applicationSelfIntroductionInput: {
      get() {
        return this.applications.selfIntroduction;
      },
      set(val) {
        this.applications.selfIntroduction = val;
      }
    },

    applicationApplyReasonInput: {
      get() {
        return this.applications.applyReason;
      },
      set(val) {
        this.applications.applyReason = val;
      }
    },

    applicationSkillEvaluation: {
      get() {
        return this.applications.skillEvaluation;
      },
      set(val) {
        this.applications.skillEvaluation = val;
      }
    },

    applicationGolfMemory: {
      get() {
        return this.applications.golfMemory;
      },
      set(val) {
        this.applications.golfMemory = val;
      }
    },

    applicationOtherClub: {
      get() {
        return this.applications.otherClub;
      },
      set(val) {
        this.applications.otherClub = val;
      }
    },

    applicationSwingVideo: {
      get() {
        return this.applications.swingVideo;
      },
      set(val) {
        this.applications.swingVideo = val;
      }
    },

    isFormValid() {
      return this.applications.name.trim().length > 0 &&
          this.applications.photo.trim().length > 0 &&
          this.applications.age.trim().length > 0 &&
          this.applications.studentId.trim().length > 0 &&
          this.applications.major.trim().length > 0 &&
          this.applications.phoneNumber.trim().length > 0 &&
          this.applications.email.trim().length > 0 &&
          this.applications.golfDuration >= 0 &&
          this.applications.roundCount >= 0 &&
          (typeof this.applications.lessonStatus === 'boolean') &&
          (typeof this.applications.clubStatus === 'boolean') &&
          this.applications.selfIntroduction.trim().length > 0 &&
          this.applications.applyReason.trim().length > 0 &&
          this.applications.skillEvaluation.trim().length > 0 &&
          this.applications.golfMemory.trim().length > 0 &&
          this.applications.otherClub.trim().length > 0 &&
          this.applications.swingVideo.trim().length > 0;
    }


  },

}
</script>


<style lang="scss" scoped>

.file-upload-container {
  display: flex;
  flex-direction: column;
}

img {
  max-width: 100px;
}

.profile-info {
  margin-top: 30px;
}

.profile-info, .application-body, .application-footer {
  width: 50%;
  border-collapse: collapse;
}

table {
  margin: 0 auto;
  font-size: 12px;
  max-width: 70%;
}

table th, table td {
  border: 1px solid #ddd;
  padding: 10px;
  padding-top: 20px;
  text-align: center;
}

table th {
  background-color: gray;
  color: #fff;
}

.application-footer {
  margin-bottom: 30px;
}

@media (max-width: 1300px) {
  .profile-info, .application-body, .application-footer {
    max-width: 90%;
    width: 90%;
  }
}

textarea {
  width: 100%;
  border: none;
  outline: none;
  resize: none;
  margin-top: 10px;
}

.apply-button {
  color: white;
  font-weight: bold;
  margin: 0 auto;
  width: 10%;
  height: 50px;
  margin-top: 20px;
  margin-bottom: 20px;
  border-radius: 10px;
  border: 1px solid #143673;
  background-color: #143673;
  transition: background-color 0.3s;
}

button:hover {
  background-color: #1a5cc8;
  border-color: #1a5cc8;
}

.before-apply {
  font-size: 12px;
}

.apply-photo {
  min-width: 100px;
  min-height: 100px;
}

.error-message {
  color: red;
  font-size: 12px;
  margin-top: 5px;
}

.photo-button {
  margin: 0 auto;
  margin-top: 5px;
  width: 30%;
}


</style>

// src/components/application/ApplicationForm.tsx
import { getAvailability, getInterviewTimes, getRecruit } from '@/components/applyinfo/api'
import AsyncState from '@/components/common/AsyncState'
import { confirmAction } from '@/components/common/ConfirmDialog'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { useAction } from '@/hooks/useAction'
import { useQuery } from '@/hooks/useQuery'
import { formatDateTime, formatPhoneNumber, isHttpUrl, seoulDateTime } from '@/lib/format'
import type { ActivityClub } from '@/types/api'
import { useEffect, useState } from 'react'
import { Link } from 'react-router'
import ActivityClubs from './ActivityClubs'
import { IMAGE_TYPES, sendEmailConfirmation, submitApplication, uploadPhoto } from './api'
import './ApplicationForm.css'

export const essayFields = [
	[
		'selfIntroduction',
		'간략하게 자기소개 부탁드립니다. (군대 계획이나 교환학생 계획이 있다면 적어주세요)',
	],
	['applyReason', '연세 골프에 지원하게 된 동기를 작성해주세요'],
	['skillEvaluation', '현재 본인의 골프 실력을 객관적으로 평가해주세요.'],
	['golfMemory', '골프와 관련된 추억이 있으시다면 말씀해주세요'],
] as const

export default function ApplicationForm({ preview = false }: { preview?: boolean }) {
	const query = useQuery(`application-form:${preview}`, async (signal) => {
		const [recruit, available] = await Promise.all([getRecruit(signal), getAvailability(signal)])
		const times = recruit ? await getInterviewTimes(recruit.id, signal) : []
		return { recruit, available, times }
	})
	const [values, setValues] = useState({
		name: '',
		email: '',
		phoneNumber: '',
		studentId: '',
		major: '',
		birthDate: '',
		selfIntroduction: '',
		applyReason: '',
		skillEvaluation: '',
		golfMemory: '',
		swingVideo: '',
	})
	const [clubs, setClubs] = useState<(ActivityClub & { key: string })[]>([])
	const [selectedTimes, setSelectedTimes] = useState<number[]>([])
	const [photo, setPhoto] = useState({ url: '', key: '' })
	const [confirmedEmail, setConfirmedEmail] = useState('')
	const [submitted, setSubmitted] = useState(false)
	const upload = useAction()
	const confirmation = useAction()
	const submission = useAction()
	useEffect(
		() => () => {
			if (photo.url) URL.revokeObjectURL(photo.url)
		},
		[photo.url],
	)

	function update(key: keyof typeof values, value: string) {
		setValues((current) => ({ ...current, [key]: value }))
	}
	if (query.loading || query.error) return <AsyncState {...query} retry={query.reload} />
	if (!preview && (!query.data?.available || !query.data.recruit))
		return (
			<div className="page-container">
				<h1>지금은 모집기간이 아닙니다.</h1>
				<Link to="/apply">모집 알림 등록하기</Link>
			</div>
		)
	if (submitted)
		return (
			<div className="page-container">
				<h1>지원서가 제출되었습니다.</h1>
				<p>
					{values.email}로 접수 메일을 보내드립니다. 10분 내로 메일을 받지 못했다면 인스타그램으로
					문의해 주세요.
				</p>
				<Link to="/">홈으로</Link>
			</div>
		)
	const valid =
		Object.values(values).every((value) => value.trim()) &&
		/^\d{1,11}$/.test(values.studentId) &&
		values.phoneNumber.replace(/\D/g, '').length >= 10 &&
		photo.key &&
		isHttpUrl(values.swingVideo) &&
		(!query.data?.times.length || selectedTimes.length > 0)
	return (
		<div className="scope-ApplicationForm">
			<form
				onSubmit={(event) => {
					event.preventDefault()
					if (!valid || preview || upload.pending || !query.data?.recruit) return
					const semester = query.data.recruit.semester
					void submission.run(async () => {
						if (
							!(await confirmAction(
								'지원서를 제출하시겠습니까?',
								`결과가 발송될 이메일을 확인해 주세요: ${values.email.trim()}`,
							))
						)
							return
						await submitApplication({
							...values,
							name: values.name.trim(),
							email: values.email.trim(),
							photoKey: photo.key,
							studentId: Number(values.studentId),
							phoneNumber: values.phoneNumber.replace(/\D/g, ''),
							activityClubs: clubs.map(({ key: _key, ...club }) => club),
							semester,
							availableInterviewTimeIds: selectedTimes,
							submitTime: seoulDateTime(),
						})
						setSubmitted(true)
					})
				}}
			>
				<div className="section-spacer" />
				<div className="form-header">
					<h1>연세 골프 지원서</h1>
					<div className="notice-text">* 지원서는 임시저장되지 않습니다.</div>
					{preview && (
						<output>지원서 양식 미리보기입니다. 제출과 이메일 발송은 실행되지 않습니다.</output>
					)}
				</div>
				<fieldset
					disabled={submission.pending}
					style={{ border: 0, padding: 0, margin: 0, minWidth: 0 }}
				>
					<div className="default_info">
						<div className="section-title">지원자 정보</div>
						<div className="photo-upload-section">
							<div className="photo-container">
								<div className="file-upload-container">
									{!photo.url && (
										<>
											<Input
												type="file"
												aria-label="지원자 사진"
												accept={IMAGE_TYPES.join(',')}
												disabled={upload.pending}
												onChange={(event) => {
													const input = event.currentTarget
													const file = input.files?.[0]
													if (file)
														void upload.run(async () => {
															try {
																const key = preview ? 'preview' : await uploadPhoto(file)
																setPhoto({ url: URL.createObjectURL(file), key })
															} finally {
																input.value = ''
															}
														})
												}}
											/>
											<div className="upload-placeholder">
												<div className="upload-icon">👤</div>
												<div className="upload-text">지원자 사진</div>
												<div className="upload-hint">
													{upload.pending ? '업로드 중…' : '클릭하여 업로드 (10MB 이하)'}
												</div>
											</div>
										</>
									)}
								</div>
								{photo.url && (
									<div className="photo-display">
										<img className="apply-photo" src={photo.url} alt="지원자 사진" />
										<Button
											type="button"
											variant="destructive"
											size="icon-sm"
											className="photo-delete-btn size-8 rounded-full p-0"
											aria-label="사진 삭제"
											onClick={() => setPhoto({ url: '', key: '' })}
										>
											×
										</Button>
									</div>
								)}
							</div>
							<AsyncState error={upload.error} />
						</div>
						{(
							[
								['name', '이름', 'text', 10],
								['email', '이메일', 'email', 254],
								['phoneNumber', '전화번호', 'tel', 13],
								['studentId', '학번', 'text', 11],
								['major', '전공', 'text', 10],
								['birthDate', '생년월일', 'date', undefined],
							] as const
						).map(([key, label, type, maxLength]) => (
							<div className="info-field" key={key}>
								<Label htmlFor={`application-${key}`}>{label}</Label>
								<div
									className={
										key === 'email'
											? 'email-container grid grid-cols-[minmax(0,1fr)_auto] max-md:grid-cols-1'
											: undefined
									}
								>
									<Input
										id={`application-${key}`}
										type={type}
										required
										maxLength={maxLength}
										value={values[key]}
										placeholder={`${label}을 입력해주세요`}
										onChange={(event) =>
											update(
												key,
												key === 'phoneNumber'
													? formatPhoneNumber(event.target.value)
													: key === 'studentId'
														? event.target.value.replace(/\D/g, '')
														: event.target.value,
											)
										}
									/>
									{key === 'email' && (
										<Button
											type="button"
											variant="outline"
											className="email-confirm-btn w-fit"
											disabled={
												preview ||
												confirmation.pending ||
												!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.email.trim()) ||
												confirmedEmail === values.email.trim()
											}
											onClick={() =>
												void confirmation.run(async () => {
													const email = values.email.trim()
													await sendEmailConfirmation(email)
													setConfirmedEmail(email)
												})
											}
										>
											{confirmation.pending
												? '발송 중…'
												: confirmedEmail === values.email.trim() && confirmedEmail
													? '발송 완료'
													: '이메일 확인'}
										</Button>
									)}
								</div>
							</div>
						))}
						<AsyncState error={confirmation.error} />
						<div className="section-spacer" />
						{essayFields.map(([key, label]) => (
							<div className="info-field" key={key}>
								<Label htmlFor={key}>{label}</Label>
								<Textarea
									id={key}
									required
									rows={6}
									maxLength={500}
									placeholder="최대 500자까지 작성 가능합니다."
									value={values[key]}
									onChange={(event) => update(key, event.target.value)}
								/>
								<small>{values[key].length} / 500</small>
							</div>
						))}
						<ActivityClubs value={clubs} onChange={setClubs} />
						<div className="info-field">
							<Label htmlFor="swingVideo">
								본인의 스윙 영상이 담긴 url을 적어주세요 (유튜브, 인스타 등)
							</Label>
							<Input
								id="swingVideo"
								type="url"
								required
								maxLength={500}
								value={values.swingVideo}
								placeholder="비공개 영상이 아닌지 확인해주세요"
								onChange={(event) => update('swingVideo', event.target.value)}
							/>
						</div>
						{Boolean(query.data?.times.length) && (
							<fieldset className="info-field" style={{ border: 0 }}>
								<legend>면접 가능 시간을 선택해주세요 (복수 선택 가능)</legend>
								<div className="interview-time-list">
									{query.data?.times.map((time) => (
										<div className="interview-time-item" key={time.id}>
											<Label
												htmlFor={`interview-time-${time.id}`}
												className="checkbox-label flex cursor-pointer items-center gap-3"
											>
												<Checkbox
													id={`interview-time-${time.id}`}
													checked={selectedTimes.includes(time.id)}
													disabled={submission.pending}
													onCheckedChange={(checked) =>
														setSelectedTimes((ids) =>
															checked === true
																? [...ids, time.id]
																: ids.filter((id) => id !== time.id),
														)
													}
												/>
												<span className="checkbox-text">
													{formatDateTime(time.interviewDateTime)}
												</span>
											</Label>
										</div>
									))}
								</div>
								{selectedTimes.length === 0 && <p>최소 1개 이상의 면접 시간을 선택해주세요.</p>}
							</fieldset>
						)}
					</div>
				</fieldset>
				<div className="form-footer">
					<div className="notice-text">
						* 지원서 제출 전 이메일과 전화번호를 다시 한번 확인해주세요.
					</div>
					<div className="notice-text">* 결과는 이메일로 전송해드립니다.</div>
				</div>
				<AsyncState error={submission.error} />
				<Button
					className="apply-button mb-5 min-h-12 min-w-40 rounded-lg text-base"
					type="submit"
					disabled={preview || !valid || submission.pending || upload.pending}
				>
					{submission.pending ? '제출 중…' : '지원서 제출'}
				</Button>
			</form>
		</div>
	)
}
