// src/components/home/ContactInfo.vue
<template>
  <div class="white-container"></div>
  <div class="contact-card">
    <h1>지금 바로 함께 해요</h1>
    <div class="contact-detail">상세 문의사항</div>
    <p>
      INSTAGRAM :
      <a href="https://www.instagram.com/yonsei__golf" target="_blank">@yonsei__golf</a>
    </p>
    <div class="buttons">
      <router-link to="/recruit">
        <button>
          &nbsp;&nbsp;&nbsp;모집안내&nbsp;&nbsp;&nbsp;
        </button>
      </router-link>
      &nbsp;&nbsp;
      <router-link to="/apply">
        <button>
          &nbsp;&nbsp;&nbsp;지원하기&nbsp;&nbsp;&nbsp;
        </button>
      </router-link>
    </div>
  </div>
  <div class="white-container"></div>
</template>

<script>
export default {
  name: 'ContactInfo'
}
</script>

<style lang="scss" scoped>

.white-container{
  height: 150px;
  color: white;
}

.contact-card {
  //width: 80%;
  max-width: 600px;
  margin: 0 auto;
  padding: 20px;
  text-align: center;

  font-family: 'Pretendard-Regular', sans-serif;
}

h1 {
  font-size: 32px;
  margin-bottom: 30px;
  color: #08366f;
  font-weight: bold;

  font-family: 'GmarketSansMedium', sans-serif;
}

.contact-detail {
  font-size: 20px;
  margin-top: 20px;
  margin-bottom: 20px;
  font-weight: bold;
  color: #4d4d4d;
}

p {
  font-size: 16px;
  color: #4d4d4d;
  font-weight: 500;
}

.buttons {
  margin-top: 20px;
}

button {
  padding: 10px 20px;

  background-color: white;
  color: #08366f;

  border: 2px solid #08366f;
  border-radius: 30px;
  cursor: pointer;

  transition: background-color 0.3s ease;
  margin-top: 20px;
  margin-bottom: 40px;
}

button:hover {
  background-color: #094a7a;
  color: white;
}

.buttons button {
  margin-right: 20px;
  font-size: 24px;
}

.buttons button:last-child {
  margin-right: 0;
}

a{
  color: #08366f;
  text-decoration: none;
  &:hover {
    text-decoration: underline;
  }
}
</style>

// src/components/home/ContactInfo.tsx
import { Button } from '@/components/ui/button'
import { Link } from 'react-router'
import './ContactInfo.css'

export default function ContactInfo() {
	return (
		<div className="scope-ContactInfo">
			<div className="white-container" />
			<div className="contact-card">
				<h1>지금 바로 함께 해요</h1>
				<div className="contact-detail">상세 문의사항</div>
				<p>
					INSTAGRAM :
					<a href="https://www.instagram.com/yonsei__golf" target="_blank" rel="noreferrer">
						@yonsei__golf
					</a>
				</p>
				<div className="buttons">
					<Button asChild variant="outline" size="lg">
						<Link to="/recruit">모집안내</Link>
					</Button>
					&nbsp;&nbsp;
					<Button asChild size="lg">
						<Link to="/apply">지원하기</Link>
					</Button>
				</div>
			</div>
			<div className="white-container" />
		</div>
	)
}
