// src/components/home/HomePage.vue
<template>
  <div>
    <MainInfo></MainInfo>
    <ClubIntroduction></ClubIntroduction>
    <ClubActivityIntroduction></ClubActivityIntroduction>
    <ContactInfo></ContactInfo>
  </div>
</template>

<script>
import MainInfo from './MainInfo.vue'
import ClubIntroduction from './ClubIntroduction.vue'
import ClubActivityIntroduction from './ClubActivityIntroduction.vue'
import ContactInfo from "./ContactInfo.vue";

export default {

  components: {
    MainInfo,
    ClubIntroduction,
    ClubActivityIntroduction,
    ContactInfo,
  }

}

</script>

<style lang="scss" scoped>

</style>

// src/components/home/HomePage.tsx
import ClubActivityIntroduction from '@/components/home/ClubActivityIntroduction'
import ClubIntroduction from '@/components/home/ClubIntroduction'
import ContactInfo from '@/components/home/ContactInfo'
import MainInfo from '@/components/home/MainInfo'

export default function HomePage() {
	return (
		<div className="scope-HomePage">
			<div>
				<MainInfo />
				<ClubIntroduction />
				<ClubActivityIntroduction />
				<ContactInfo />
			</div>
		</div>
	)
}
